
  - name: install redis release
    ansible.builtin.command: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.6.rpm -y

  - name: Reset default Redis module
    ansible.builtin.command: dnf module reset redis -y

  - name: Enable default Redis module
    ansible.builtin.command: dnf module enable redis:remi-6.2 -y
    
  - name: "Install {{component}}""
    ansible.builtin.package:
     name: "{{component}}"
     state: present

  - name: "allow {{component}} connections"
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'

  - name: "start and enable {{component}}"
    ansible.builtin.service:
      name: "{{component}}"
      state: restarted
      enabled: yes