  - name: copy mongodb
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-org-shell 
      state: present

  - name: load catalogue data
    ansible.builtin.command: mongo --host mongodb.manacars.shop  < /app/schema/catalogue.js