  - name: copy catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: load service
    ansible.builtin.systemd_service:
      daemon_reload: true