  - name: create user
    ansible.builtin.user:
      name: roboshop
       
  - name: create directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: create directory
    ansible.builtin.file:
      path: /app
      state: directory

  - name: "download {{component}} applications"
    ansible.builtin.get_url:
      url: "https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip" 
      dest: /tmp

  - name: "extract {{component}} applcations"
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes